# Generated by Django 5.2.10 on 2026-01-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('severity', models.CharField(choices=[('critical', '致命'), ('major', '严重'), ('minor', '一般'), ('trivial', '轻微')], default='minor', max_length=20, verbose_name='严重程度')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('rejected', '已驳回'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('module', models.CharField(blank=True, default='', max_length=100, verbose_name='所属模块')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='版本号')),
                ('solution', models.TextField(blank=True, default='', verbose_name='解决说明')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='驳回原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'BUG',
                'verbose_name_plural': 'BUG',
                'db_table': 'bugs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='bug_attachments/%Y/%m/', verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': 'BUG附件',
                'verbose_name_plural': 'BUG附件',
                'db_table': 'bug_attachments',
            },
        ),
    ]
