# Generated by Django 3.2.22 on 2026-03-04 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0003_update_module_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('status_change', '状态变更'), ('assign', '分配'), ('delete', '删除')], max_length=20, verbose_name='操作类型')),
                ('field_name', models.CharField(blank=True, default='', max_length=50, verbose_name='变更字段')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='原值')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='新值')),
                ('description', models.TextField(blank=True, default='', verbose_name='操作描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bugs.bug', verbose_name='BUG')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': 'BUG操作历史',
                'verbose_name_plural': 'BUG操作历史',
                'db_table': 'bug_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
